# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "http://localhost:4000"
baseurl: ""

gems: [jekyll-paginate]

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Name of website
title: Gnome (& goblin)

# Short description of your site
description: About Gnome desktop evironment development in particular and software engineering. Stay crousty, even in milk.

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Homepage: "index.html"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/me.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Laurent Callarec
  email: l.callarec@gmail.com
  facebook: ~
  github: lcallarec
  twitter: ~
  linkedin: https://www.linkedin.com/in/laurent-callarec-92104483
  stackoverflow: ~

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "lcallarec.github.io"


# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-100412922-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
